### ISSUE TITLE
TypeError: string indices must be integers

### ISSUE THREAD

**Issue by casperdcl** [matplotlib/ipympl#269]
## Describe the issue

Can't run the first two cells of https://github.com/matplotlib/ipympl/blob/master/examples/ipympl.ipynb

```python
TypeError                                 Traceback (most recent call last)
~/py2/envs/py37/lib/python3.7/site-packages/ipympl/backend_nbagg.py in _handle_message(self, object, content, buffers)
    208     def _handle_message(self, object, content, buffers):
    209         # Every content has a "type".
--> 210         if content['type'] == 'closing':
    211             self._closed = True
    212         elif content['type'] == 'initialized':

TypeError: string indices must be integers
```

## Versions

```
jupyter core     : 4.6.3
jupyter-notebook : 5.7.8
ipykernel        : 5.3.4
Python 3.7.8 | packaged by conda-forge | (default, Jul 31 2020, 02:25:08) [GCC 7.5.0]
ipympl==0.5.8
```

from https://github.com/matplotlib/matplotlib/issues/18638#issuecomment-702976649

**Comment by Rashmi-Chitriv** [comment]
is this issue resolved? I am getting same error on lmplot 
sns.lmplot(y='tip', x='total_bill', data='tips')

**Comment by thomasaarholt** [comment]
The first comment works fine here. This can be closed.

@Rashmi-Chitriv your error has nothing to do with ipympl :) It is a seaborn error. I get the same error if I'm using the `%matplotlib inline` backend, or just run `import seaborn as sns; sns.lmplot(y='tip', x='total_bill', data='tips')` in the python terminal.

Your error comes because `data` doesn't expect a string like `"tips"`, but a pandas array. You can [see that here](https://seaborn.pydata.org/generated/seaborn.lmplot.html#seaborn.lmplot).

**Comment by Rashmi-Chitriv** [comment]
thanks much for prompt response.  It was a syntax error in the lmplot
sns.lmplot(y='tip', x='total_bill', data='tips')

data = tips is enclosed in comma in my original code. I removed these and code started working.

**Comment by martinRenou** [comment]
Great! Closing then. Thanks a lot for the answer @thomasaarholt
