### ISSUE TITLE
Feature req: Custom labeling in footer

### ISSUE THREAD

**Issue by bdch1234** [matplotlib/ipympl#298]
Would it be possible to add custom data showing up in the footer on mouse-over?

**Comment by thomasaarholt** [comment]
Could you expand with an example?

**Comment by bdch1234** [comment]
So in basic scatter-plot, we always see x,y coordinates. In an imshow-plot, there is an added part which shows the "height". It would be great if I could also add custom data mapping to a plot, so e.g. would show labels on mouse over scatter-points.

**Comment by ianhi** [comment]
What you're describing is a feature that would need to be implemented in core matplotlib, or you could implement yourself using matplotlib methods.  For example see the discussion here: https://github.com/matplotlib/matplotlib/issues/9957

I think that the issue is that there is probably no universally "right" way to implement what you want. 

You can likely implement something that will work for your case by following this example: https://matplotlib.org/3.3.4/gallery/images_contours_and_fields/image_zcoord.html#sphx-glr-gallery-images-contours-and-fields-image-zcoord-py

**Comment by bdch1234** [comment]
Got it, thanks for explaining. I'll look into the examples you gave.

**Comment by ianhi** [comment]
:+1:. If you try it an run into issue then https://discourse.matplotlib.org/ is probably a good place to ask further questions.
